### ISSUE TITLE
bitlbee crashes on sending message

### ISSUE THREAD

**Issue by mortzu** [majn/telegram-purple#154]
When I send a message via bitlbee it crashes with:
```
@400000005640d1470e0bb5f4 =================================================================
@400000005640d1470e0bbdc4 ==36138==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x604000099ab5 at pc 0x7fe5fe264792 bp 0x7ffc800224f0 sp 0x7ffc80021cb0
@400000005640d1470e0bc1ac READ of size 4310 at 0x604000099ab5 thread T0
@400000005640d14710cf5e1c     #0 0x7fe5fe264791 (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x2e791)
@400000005640d14710d0216c     #1 0x7fe5fda9aecc in g_utf8_substring (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x78ecc)
@400000005640d14710d92dd4     #2 0x7fe5eaf59449 in tgp_msg_send_split /home/mortzu/.var/tmp/telegram-purple/tgp-msg.c:243
@400000005640d14710d97bf4     #3 0x7fe5eaf59449 in tgp_msg_send /home/mortzu/.var/tmp/telegram-purple/tgp-msg.c:332
@400000005640d14710edb3bc     #4 0x7fe5fca58004 in serv_send_im /home/mortzu/.toast/pkg/pidgin/v2.10.11/1/src/pidgin-2.10.11/libpurple/server.c:145
@400000005640d14710fc906c     #5 0x7fe5fca32a3e in common_send /home/mortzu/.toast/pkg/pidgin/v2.10.11/1/src/pidgin-2.10.11/libpurple/conversation.c:182
@400000005640d147110598ec     #6 0x7fe5ff3e2c0c in purple_buddy_msg /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/protocols/purple/purple.c:375
@400000005640d14711081d74     #7 0x7fe5ff3d91c7 in bee_user_msg /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/protocols/bee_user.c:109
@400000005640d147110d2e54     #8 0x7fe5ff376595 in bee_irc_user_privmsg_cb /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/irc_im.c:478
@400000005640d147110d788c     #9 0x7fe5ff3762c8 in bee_irc_user_privmsg /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/irc_im.c:444
@400000005640d147111183b4     #10 0x7fe5ff3832a0 in irc_cmd_privmsg /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/irc_commands.c:338
@400000005640d1471111be4c     #11 0x7fe5ff386764 in irc_exec /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/irc_commands.c:755
@400000005640d1471115f084     #12 0x7fe5ff36f064 in irc_process /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/irc.c:397
@400000005640d1471118e26c     #13 0x7fe5ff360116 in bitlbee_io_current_client_read /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/bitlbee.c:211
@400000005640d147111a6524     #14 0x7fe5ff3b4d1c in gaim_io_invoke /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/lib/events_glib.c:86
@400000005640d147111aa78c     #15 0x7fe5fda6bb6c in g_main_context_dispatch (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x49b6c)
@400000005640d147111ae9f4     #16 0x7fe5fda6bf47 (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x49f47)
@400000005640d147111b3bfc     #17 0x7fe5fda6c271 in g_main_loop_run (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4a271)
@400000005640d147111b5f24     #18 0x7fe5ff3b4c45 in b_main_run /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/lib/events_glib.c:59
@400000005640d147115727d4     #19 0x7fe5ff3aeda2 in main /home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/src/bitlbee-3.4.1/unix.c:170
@400000005640d147115821d4     #20 0x7fe5fc44ab44 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b44)
@400000005640d147115873dc     #21 0x7fe5ff35eb48 (/home/mortzu/.toast/pkg/bitlbee/v3.4.1/1/root/bin/bitlbee+0x2eb48)
@400000005640d14711589704 
@400000005640d14711595e3c 0x604000099ab5 is located 0 bytes to the right of 37-byte region [0x604000099a90,0x604000099ab5)
@400000005640d147115998d4 allocated by thread T0 here:
@400000005640d147117d1aac     #0 0x7fe5fe28a73f in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.1+0x5473f)
@400000005640d147117d709c     #1 0x7fe5fda717c9 in g_malloc (/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4f7c9)
@400000005640d147117d8bf4 
@400000005640d147117e2064 SUMMARY: AddressSanitizer: heap-buffer-overflow ??:0 ??
@400000005640d147117e5714 Shadow bytes around the buggy address:
@400000005640d147117e6e84   0x0c088000b300: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
@400000005640d147117f4174   0x0c088000b310: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
@400000005640d1471180107c   0x0c088000b320: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
@400000005640d1471180eb3c   0x0c088000b330: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
@400000005640d1471181dd6c   0x0c088000b340: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
@400000005640d1471182f2c4 =>0x0c088000b350: fa fa 00 00 00 00[05]fa fa fa fd fd fd fd fd fa
@400000005640d14711842f2c   0x0c088000b360: fa fa 00 00 00 00 05 fa fa fa fd fd fd fd fd fa
@400000005640d14711854484   0x0c088000b370: fa fa fd fd fd fd fd fa fa fa fd fd fd fd fd fa
@400000005640d147118655f4   0x0c088000b380: fa fa 00 00 00 00 00 fa fa fa fd fd fd fd fd fa
@400000005640d14711874c0c   0x0c088000b390: fa fa fd fd fd fd fd fa fa fa 00 00 00 00 05 fa
@400000005640d14711881b14   0x0c088000b3a0: fa fa 00 00 00 00 05 fa fa fa fd fd fd fd fd fa
@400000005640d1471188ea1c Shadow byte legend (one shadow byte represents 8 application bytes):
@400000005640d1471189018c   Addressable:           00
@400000005640d14711891514   Partially addressable: 01 02 03 04 05 06 07 
@400000005640d1471189865c   Heap left redzone:       fa
@400000005640d147118999e4   Heap right redzone:      fb
@400000005640d1471189b924   Freed heap region:       fd
@400000005640d1471189ccac   Stack left redzone:      f1
@400000005640d1471189e034   Stack mid redzone:       f2
@400000005640d1471189f7a4   Stack right redzone:     f3
@400000005640d147118a0b2c   Stack partial redzone:   f4
@400000005640d147118a2a6c   Stack after return:      f5
@400000005640d147118a3df4   Stack use after scope:   f8
@400000005640d147118a517c   Global redzone:          f9
@400000005640d147118a68ec   Global init order:       f6
@400000005640d147118a7c74   Poisoned by user:        f7
@400000005640d147118a8ffc   Contiguous container OOB:fc
@400000005640d147118aa384   ASan internal:           fe
@400000005640d147118abedc ==36138==ABORTING
```

**Comment by majn** [comment]
What kind of message did you send?

**Comment by mortzu** [comment]
"test"

**Comment by majn** [comment]
Fixed https://github.com/majn/telegram-purple/commit/643a30faa74ad2a51fcf7cafe926a87c283a8b56
