### ISSUE TITLE
Pidgin crashes on arch after update

### ISSUE THREAD

**Issue by githubtefo** [majn/telegram-purple#223]
I've updated to pidgin 2.10.12-1 on Arch and the telegram protocol disappeared from the options.
So I compiled and installed from source telegram-purple again, but now pidgin crashes when it is trying to connect. I tried to install it from the arch tarball, but with the same result.
Someone else is experimenting the same issue?
Thanks!

**Comment by EionRobb** [comment]
Can you get a debug log from pidgin (run it from a terminal with the --debug flag), and what version of the telegram-purple plugin are you using?

**Comment by BenWiederhake** [comment]
Also try `pidgin -d | tee debug.log`, because I don't think the flag was called `--debug` :P

> the telegram protocol disappeared from the options
Probably a linking issue again. *sigh*

**Comment by githubtefo** [comment]
I've got the debug log. I attach it.
(telegram-purple-1.2.4-1-i686.pkg.tar)

[debug.log.txt](https://github.com/majn/telegram-purple/files/89091/debug.log.txt)

Thanks!

**Comment by BenWiederhake** [comment]
From the log, it looks like it simply can't connect due to ping timeout (= it doesn't receive any response from any server at all), and then you closed pidgin manually.

So is this issue about the "ping timeout" thing? Or something else?
If it is "something else": can you send a log from when it shows the unintended behavior?

**Comment by githubtefo** [comment]
It looks like a "ping timeout" thing: Pidgin freezes during a few minutes and then shows "lost connection with the server" message.
Sorry, I missunderstood the issue because this was the first time I wait the sufficient time to see the message.
But the ping timeout problem only happens with the telegram protocol after update pidgin.

**Comment by BenWiederhake** [comment]
> Pidgin freezes during a few minutes

Huh?! That shouldn't happen. I guess that something in tgp "hangs" and makes pidgin unresponsive for long enough, and when it finally works again, tgl thinks that the connection is broken.

Ideally, we should somehow find out which component "hangs" or what actually happens. If you can use the command-line, this shouldn't be too hard. So here it is:

    $ gdb pidgin
    (gdb) run
    ...
    Ctrl-Z
    (gdb) bt full 20

Hmm. That doesn't quite explain it.

- `$ gdb pidgin` Here you see the shell prompt (`$ `) and enter `gdb pidgin`
- `(gdb) run` Here you see the gdb prompt (`(gdb) `) and enter `run`
- Then you wait a few seconds, until pidgin locks up in the way you observed it.
- As soon as this happens, go back to the terminal, and hit Ctrl-Z. This effectively means "Hold on!" and stops/interrupts the running process. You will probably see something like this:
```^Z
Program received signal SIGTSTP, Stopped (user).
0x00007ffff7aef170 in __nanosleep_nocancel () at ../sysdeps/unix/syscall-template.S:81```
- Now you see the prompt again and enter `bt full 20`, which essentially tells gdb to output "a lot of interesting info, but only for the first 20 frames".
- Copy&paste that info, we can make sense of it.

Note that if gdb stops pidgin, pidgin obviously can't respond anymore. So try to carefully distinguish between "gdb had another question (visible on the console) and made pidgin look like it hangs" and "nope, pidgin hung itself, without any aid from gdb (in this case, you don't see any `(gdb)` prompt on the console right after you `run`)"

For the record: @majn, I assume that this is a hang somewhere in tgp.

**Comment by githubtefo** [comment]
This is the output of gdb:
````
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
^Z
Program received signal SIGTSTP, Stopped (user).
0xb653501a in ?? () from /usr/lib/libgcrypt.so.20
(gdb) bt full 20
#0  0xb653501a in ?? () from /usr/lib/libgcrypt.so.20
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0xb8373e6

**Comment by BenWiederhake** [comment]
Hmm. Could you try again?
*(Oh no please don't let the hang be in gcrypt, please don't let the hang be in gcrypt!)*

**Comment by githubtefo** [comment]
````
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
^Z
Program received signal SIGTSTP, Stopped (user).
0xb6534fd2 in ?? () from /usr/lib/libgcrypt.so.20
(gdb) bt full 20
#0  0xb6534fd2 in ?? () from /usr/lib/libgcrypt.so.20
No symbol table info available.
Backtrace stopped: Cannot access memory at address 0xd3b2b9bd
````
I'm sorry!

**Comment by BenWiederhake** [comment]
Not your fault; it's just that I have no idea how to go about this :(

@majn: Halp!

**Comment by majn** [comment]
No idea, sounds like a packaging issue.

**Comment by majn** [comment]
If you are using https://aur.archlinux.org/packages/telegram-purple/, I just noticed that they still list openssl as dependency, so there is at least something going wrong with that build.

**Comment by githubtefo** [comment]
Remember I also tried to compile from source.
Now Im using the option "./configure --disable-gcrypt" with no problems.

**Comment by majn** [comment]
Are you sure that you didn't just miss libgcrypt in both cases, do you have a log of those crashes or do you remember what error happened?

Why are you compiling with --disable-gcrypt? Arch is bleeding edge, so I'm sure that is has libgcrypt20 (>=1.60) available. If its available you should try to use it, --disable-gcrypt is only a workaround for distributions with old packages.

**Comment by psamim** [comment]
I have the same problem on Arch.

**Comment by BenWiederhake** [comment]
@majn: most of your question already have been answered:

> do you have a log of those crashes or do you remember what error happened?

Log is posted, error was "connection lost: ping timeout" or equivalent.

> Why are you compiling with --disable-gcrypt?

Because that's actually a good idea because it looks like the hand is in gcrypt, so disabling gcrypt might get rid of the hang. Judging from the lack of response, I'd say it does.

**Comment by psamim** [comment]
This is my log from pidgin -d.

[debug.log.txt](https://github.com/majn/telegram-purple/files/95532/debug.log.txt)

**Comment by psamim** [comment]
Here is another log when Pidgin crashed.
[debug2.log.txt](https://github.com/majn/telegram-purple/files/95546/debug2.log.txt)

**Comment by psamim** [comment]
It seems the problem is gone. I removed ~/.purple .

**Comment by BenWiederhake** [comment]
That really *really* shouldn't be related. I'd rather fix the underlying problem than just tell everyone "hey just delete some random folder that contains some important stuff and has quite a few side effects"

**Comment by githubtefo** [comment]
Sorry, I didn't respond because I was not be around here.
Just in case I checked libgcrypt and it looks to be updated.
````
$ sudo pacman -S libgcrypt
advertencia: libgcrypt-1.6.4-1 está actualizado -- reinstalando
resolviendo dependencias...
buscando conflictos entre paquetes....

Paquetes (1) libgcrypt-1.6.4-1

Tamaño total de la descarga:    0,38 MiB
Tamaño total de la instalación:  0,90 MiB
Tamaño neto tras actualizar:    0,00 MiB

:: ¿Continuar con la instalación? [S/n] n
````
I may use the old certificates for a while, dont worry about me. Actually I've got some more complex issues in my Arch netbook, regarding the screws that holding the flatscreen haha...

**Comment by psamim** [comment]
May or may not be related to this issue. Pidgin crashed again and it is related to to telegram-purple. Here is my debug log.

[debug.log.txt](https://github.com/majn/telegram-purple/files/97209/debug.log.txt)

**Comment by majn** [comment]
@psamim this issue is fixed on dev-1.2.5

**Comment by majn** [comment]
To get an overview of the multiple issues that seem to be discussed in this issue':

Not connecting due to AUTH_KEY_UNREGISTERED, SESSION_REVOKED is fixed in 1.2.5.

The arch issue about the plugin working after an upgrade seemed to be a mistake by the arch packager (not listing libgcrypt as dependency, while the binary actually linked against it). This appears to be fixed in the newer package versions.

The arch and windows connection timeout doesn't seem to be fixed, since I haven't figured out the cause for those yet.

**Comment by majn** [comment]
Connection fails, SMS prompt is not appearing.

telegram-purple v 1.2.3_final, from the github page pidgin v 2.10.12, ibpurple, same OS Windows 7

Pidgin Debug Log : 1/6/2016 10:45:36 AM
(10:42:16) util: Writing file accounts.xml to directory C:\Users\XXXXXXX\AppData\Roaming\.purple
(10:42:16) util: Writing file C:\Users\XXXXXXX\AppData\Roaming\.purple\accounts.xml
(10:42:16) account: Connecting to account +1XXXXXXX.
(10:42:16) connection: Connecting. gc = 100D8C18
(10:42:16) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
(10:42:16) prpl-telegram: base configuration path: 'C:\Users\XXXXXXX\AppData\Roaming\.purple\telegram-purple\+1XXXXXXX'
(10:42:16) prpl-telegram: trying global pubkey at C:\Program Files (x86)\Pidgin/server.tglpub
(10:42:16) prpl-telegram: read pubkey file: n_len=256 e=65537
(10:42:16) prpl-telegram: using global pubkey
(10:42:16) prpl-telegram: 'direct' public key loaded successfully
(10:42:16) prpl-telegram: initializing empty auth file
(10:42:16) prpl-telegram: DC1 '' update: 149.154.175.50:443
(10:42:16) prpl-telegram: DC2 '' update: 149.154.167.51:443
(10:42:16) prpl-telegram: DC3 '' update: 149.154.175.100:443
(10:42:16) prpl-telegram: DC4 '' update: 149.154.167.91:443
(10:42:16) prpl-telegram: DC5 '' update: 149.154.171.5:443
(10:42:16) dnsquery: Performing DNS lookup for 149.154.175.50
(10:42:16) dnsquery: Performing DNS lookup for 149.154.167.51
(10:42:16) dnsquery: Performing DNS lookup for 149.154.175.100
(10:42:16) dnsquery: Performing DNS lookup for 149.154.167.91
(10:42:16) dnsquery: Performing DNS lookup for 149.154.171.5
(10:42:16) dnsquery: IP resolved for 149.154.175.50
(10:42:16) proxy: Attempting connection to 149.154.175.50
(10:42:16) proxy: Connecting to 149.154.175.50:443 with no proxy
(10:42:16) proxy: Connection in progress
(10:42:16) dnsquery: IP resolved for 149.154.167.51
(10:42:16) proxy: Attempting connection to 149.154.167.51
(10:42:16) proxy: Connecting to 149.154.167.51:443 with no proxy
(10:42:16) proxy: Connection in progress
(10:42:16) dnsquery: IP resolved for 149.154.175.100
(10:42:16) proxy: Attempting connection to 149.154.175.100
(10:42:16) proxy: Connecting to 149.154.175.100:443 with no proxy
(10:42:16) proxy: Connection in progress
(10:42:16) dnsquery: IP resolved for 149.154.167.91
(10:42:16) proxy: Attempting connection to 149.154.167.91
(10:42:16) proxy: Connecting to 149.154.167.91:443 with no proxy
(10:42:16) proxy: Connection in progress
(10:42:16) dnsquery: IP resolved for 149.154.171.5
(10:42:16) proxy: Attempting connection to 149.154.171.5
(10:42:16) proxy: Connecting to 149.154.171.5:443 with no proxy
(10:42:16) proxy: Connection in progress
(10:42:16) proxy: Connecting to 149.154.175.50:443.
(10:42:16) proxy: Connected to 149.154.175.50:443.
(10:42:16) proxy: Connecting to 149.154.167.51:443.
(10:42:16) proxy: Connected to 149.154.167.51:443.
(10:42:16) proxy: Connecting to 149.154.175.100:443.
(10:42:16) proxy: Connected to 149.154.175.100:443.
(10:42:16) prpl-telegram: outbound rpc connection from dc #2 becomed ready
(10:42:16) proxy: Connecting to 149.154.167.91:443.
(10:42:16) proxy: Connected to 149.154.167.91:443.
(10:42:16) proxy: Connecting to 149.154.171.5:443.
(10:42:16) proxy: Connected to 149.154.171.5:443.
(10:42:16) prpl-telegram: outbound rpc connection from dc #1 becomed ready
(10:42:16) prpl-telegram: outbound rpc connection from dc #3 becomed ready
(10:42:16) prpl-telegram: outbound rpc connection from dc #4 becomed ready
(10:42:16) prpl-telegram: outbound rpc connection from dc #5 becomed ready
(10:42:21) util: Writing file accounts.xml to directory C:\Users\XXXXXXX\AppData\Roaming\.purple
(10:42:21) util: Writing file C:\Users\XXXXXXX\AppData\Roaming\.purple\accounts.xml
(10:42:32) prpl-telegram: ping alarm
(10:42:32) prpl-telegram: ping alarm
(10:42:32) prpl-telegram: ping alarm
(10:42:32) prpl-telegram: ping alarm
(10:42:32) prpl-telegram: ping alarm
(10:42:47) prpl-telegram: ping alarm
(10:42:47) prpl-telegram: ping alarm
(10:42:47) prpl-telegram: ping alarm
(10:42:47) prpl-telegram: ping alarm
(10:42:47) prpl-telegram: ping alarm
(10:43:02) prpl-telegram: ping alarm
(10:43:02) prpl-telegram: ping alarm
(10:43:02) prpl-telegram: ping alarm
(10:43:02) prpl-telegram: ping alarm
(10:43:02) prpl-telegram: ping alarm
(10:43:05) network: found network ''
(10:43:05) network: Received Network Change Notification. Current network count is 1, previous count was 1.
(10:43:17) prpl-telegram: ping alarm
(10:43:17) prpl-telegram: ping alarm
(10:43:17) prpl-telegram: ping alarm
(10:43:17) prpl-telegram: ping alarm
(10:43:17) prpl-telegram: ping alarm
(10:43:32) prpl-telegram: ping alarm
(10:43:32) prpl-telegram: ping alarm
(10:43:32) prpl-telegram: ping alarm
(10:43:32) prpl-telegram: ping alarm
(10:43:32) prpl-telegram: ping alarm
(10:43:47) prpl-telegram: ping alarm
(10:43:47) prpl-telegram: fail connection: reason: ping timeout
(10:43:47) prpl-telegram: Lost connection to server ... 149.154.175.50:80
(10:43:47) connection: Connection error on 100D8C18 (reason: 0 description: Lost connection to the server...)
(10:43:47) prpl-telegram: ping alarm
(10:43:47) prpl-telegram: fail connection: reason: ping timeout
(10:43:47) prpl-telegram: Lost connection to server ... 149.154.167.51:80
(10:43:47) prpl-telegram: ping alarm
(10:43:47) prpl-telegram: fail connection: reason: ping timeout
(10:43:47) prpl-telegram: Lost connection to server ... 149.154.175.100:80
(10:43:47) prpl-telegram: ping alarm
(10:43:47) prpl-telegram: fail connection: reason: ping timeout
(10:43:47) prpl-telegram: Lost connection to server ... 149.154.167.91:80
(10:43:47) prpl-telegram: ping alarm
(10:43:47) prpl-telegram: fail connection: reason: ping timeout
(10:43:47) prpl-telegram: Lost connection to server ... 149.154.171.5:80
(10:43:47) account: Disconnecting account +1XXXXXXX (0047E280)
(10:43:47) connection: Disconnecting connection 100D8C18
(10:43:47) prpl-telegram: tgprpl_close()
(10:43:47) connection: Destroying connection 100D8C18
(10:43:52) util: Writing file accounts.xml to directory C:\Users\XXXXXXX\AppData\Roaming\.purple
(10:43:52) util: Writing file C:\Users\XXXXXXX\AppData\Roaming\.purple\accounts.xml
(10:43:58) autorecon: do_signon called
(10:43:58) autorecon: calling purple_account_connect
(10:43:58) account: Connecting to account +1XXXXXXX.
(10:43:58) connection: Connecting. gc = 100D9298
(10:43:58) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
(10:43:58) prpl-telegram: base configuration path: 'C:\Users\XXXXXXX\AppData\Roaming\.purple\telegram-purple\+1XXXXXXX'
(10:43:58) prpl-telegram: trying global pubkey at C:\Program Files (x86)\Pidgin/server.tglpub
(10:43:58) prpl-telegram: read pubkey file: n_len=256 e=65537
(10:43:58) prpl-telegram: using global pubkey
(10:43:58) prpl-telegram: 'direct' public key loaded successfully
(10:43:58) prpl-telegram: initializing empty auth file
(10:43:58) prpl-telegram: DC1 '' update: 149.154.175.50:443
(10:43:58) prpl-telegram: DC2 '' update: 149.154.167.51:443
(10:43:58) prpl-telegram: DC3 '' update: 149.154.175.100:443
(10:43:58) prpl-telegram: DC4 '' update: 149.154.167.91:443
(10:43:58) prpl-telegram: DC5 '' update: 149.154.171.5:443
(10:43:58) autorecon: done calling purple_account_connect
(10:43:58) dnsquery: Performing DNS lookup for 149.154.175.50
(10:43:58) dnsquery: Performing DNS lookup for 149.154.167.51
(10:43:58) dnsquery: Performing DNS lookup for 149.154.175.100
(10:43:58) dnsquery: Performing DNS lookup for 149.154.167.91
(10:43:58) dnsquery: Performing DNS lookup for 149.154.171.5
(10:43:58) dnsquery: IP resolved for 149.154.175.50
(10:43:58) proxy: Attempting connection to 149.154.175.50
(10:43:58) proxy: Connecting to 149.154.175.50:443 with no proxy
(10:43:58) proxy: Connection in progress
(10:43:58) dnsquery: IP resolved for 149.154.167.51
(10:43:58) proxy: Attempting connection to 149.154.167.51
(10:43:58) proxy: Connecting to 149.154.167.51:443 with no proxy
(10:43:58) proxy: Connection in progress
(10:43:58) dnsquery: IP resolved for 149.154.175.100
(10:43:58) proxy: Attempting connection to 149.154.175.100
(10:43:58) proxy: Connecting to 149.154.175.100:443 with no proxy
(10:43:58) proxy: Connection in progress
(10:43:58) dnsquery: IP resolved for 149.154.167.91
(10:43:58) proxy: Attempting connection to 149.154.167.91
(10:43:58) proxy: Connecting to 149.154.167.91:443 with no proxy
(10:43:58) proxy: Connection in progress
(10:43:58) dnsquery: IP resolved for 149.154.171.5
(10:43:58) proxy: Attempting connection to 149.154.171.5
(10:43:58) proxy: Connecting to 149.154.171.5:443 with no proxy
(10:43:58) proxy: Connection in progress
(10:43:58) proxy: Connecting to 149.154.175.50:443.
(10:43:58) proxy: Connected to 149.154.175.50:443.
(10:43:58) proxy: Connecting to 149.154.167.51:443.
(10:43:58) proxy: Connected to 149.154.167.51:443.
(10:43:58) prpl-telegram: outbound rpc connection from dc #1 becomed ready
(10:43:58) proxy: Connecting to 149.154.175.100:443.
(10:43:58) proxy: Connected to 149.154.175.100:443.
(10:43:58) proxy: Connecting to 149.154.167.91:443.
(10:43:58) proxy: Connected to 149.154.167.91:443.
(10:43:58) proxy: Connecting to 149.154.171.5:443.
(10:43:58) proxy: Connected to 149.154.171.5:443.
(10:43:58) prpl-telegram: outbound rpc connection from dc #2 becomed ready
(10:43:58) prpl-telegram: outbound rpc connection from dc #3 becomed ready
(10:43:58) prpl-telegram: outbound rpc connection from dc #4 becomed ready
(10:43:58) prpl-telegram: outbound rpc connection from dc #5 becomed ready
(10:44:07) account: Connecting to account +1XXXXXXX.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:11) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) util: Writing file accounts.xml to directory C:\Users\XXXXXXX\AppData\Roaming\.purple
(10:44:12) util: Writing file C:\Users\XXXXXXX\AppData\Roaming\.purple\accounts.xml
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:12) prefs: /pidgin/debug/height changed, scheduling save.
(10:44:14) prpl-telegram: ping alarm
(10:44:14) prpl-telegram: ping alarm
(10:44:14) prpl-telegram: ping alarm
(10:44:14) prpl-telegram: ping alarm
(10:44:14) prpl-telegram: ping alarm
(10:44:17) util: Writing file prefs.xml to directory C:\Users\XXXXXXX\AppData\Roaming\.purple
(10:44:17) util: Writing file C:\Users\XXXXXXX\AppData\Roaming\.purple\prefs.xml
(10:44:29) prpl-telegram: ping alarm
(10:44:29) prpl-telegram: ping alarm
(10:44:29) prpl-telegram: ping alarm
(10:44:29) prpl-telegram: ping alarm
(10:44:29) prpl-telegram: ping alarm
(10:44:44) prpl-telegram: ping alarm
(10:44:44) prpl-telegram: ping alarm
(10:44:44) prpl-telegram: ping alarm
(10:44:44) prpl-telegram: ping alarm
(10:44:44) prpl-telegram: ping alarm
(10:44:59) prpl-telegram: ping alarm
(10:44:59) prpl-telegram: ping alarm
(10:44:59) prpl-telegram: ping alarm
(10:44:59) prpl-telegram: ping alarm
(10:44:59) prpl-telegram: ping alarm
(10:45:14) prpl-telegram: ping alarm
(10:45:14) prpl-telegram: ping alarm
(10:45:14) prpl-telegram: ping alarm
(10:45:14) prpl-telegram: ping alarm
(10:45:14) prpl-telegram: ping alarm
(10:45:29) prpl-telegram: ping alarm
(10:45:29) prpl-telegram: fail connection: reason: ping timeout
(10:45:29) prpl-telegram: Lost connection to server ... 149.154.175.50:80
(10:45:29) connection: Connection error on 100D9298 (reason: 0 description: Lost connection to the server...)
(10:45:29) prpl-telegram: ping alarm
(10:45:29) prpl-telegram: fail connection: reason: ping timeout
(10:45:29) prpl-telegram: Lost connection to server ... 149.154.167.51:80
(10:45:29) prpl-telegram: ping alarm
(10:45:29) prpl-telegram: fail connection: reason: ping timeout
(10:45:29) prpl-telegram: Lost connection to server ... 149.154.175.100:80
(10:45:29) prpl-telegram: ping alarm
(10:45:29) prpl-telegram: fail connection: reason: ping timeout
(10:45:29) prpl-telegram: Lost connection to server ... 149.154.167.91:80
(10:45:29) prpl-telegram: ping alarm
(10:45:29) prpl-telegram: fail connection: reason: ping timeout
(10:45:29) prpl-telegram: Lost connection to server ... 149.154.171.5:80
(10:45:29) account: Disconnecting account +1XXXXXXX (0047E280)
(10:45:29) connection: Disconnecting connection 100D9298
(10:45:29) prpl-telegram: tgprpl_close()
(10:45:29) connection: Destroying connection 100D9298
(10:45:32) network: found network ''
(10:45:32) network: Received Network Change Notification. Current network count is 1, previous count was 1.
(10:45:32) autorecon: do_signon called
(10:45:32) autorecon: calling purple_account_connect
(10:45:32) account: Connecting to account +1XXXXXXX.
(10:45:32) connection: Connecting. gc = 100D7ED8
(10:45:32) prpl-telegram: tgprpl_login(): Purple is telling the prpl to connect the account
(10:45:32) prpl-telegram: base configuration path: 'C:\Users\XXXXXXX\AppData\Roaming\.purple\telegram-purple\+1XXXXXXX'
(10:45:32) prpl-telegram: trying global pubkey at C:\Program Files (x86)\Pidgin/server.tglpub
(10:45:32) prpl-telegram: read pubkey file: n_len=256 e=65537
(10:45:32) prpl-telegram: using global pubkey
(10:45:32) prpl-telegram: 'direct' public key loaded successfully
(10:45:32) prpl-telegram: initializing empty auth file
(10:45:32) prpl-telegram: DC1 '' update: 149.154.175.50:443
(10:45:32) prpl-telegram: DC2 '' update: 149.154.167.51:443
(10:45:32) prpl-telegram: DC3 '' update: 149.154.175.100:443
(10:45:32) prpl-telegram: DC4 '' update: 149.154.167.91:443
(10:45:32) prpl-telegram: DC5 '' update: 149.154.171.5:443
(10:45:32) autorecon: done calling purple_account_connect
(10:45:32) dnsquery: Performing DNS lookup for 149.154.175.50
(10:45:32) dnsquery: Performing DNS lookup for 149.154.167.51
(10:45:32) dnsquery: Performing DNS lookup for 149.154.175.100
(10:45:32) dnsquery: Performing DNS lookup for 149.154.167.91
(10:45:32) dnsquery: Performing DNS lookup for 149.154.171.5
(10:45:32) dnsquery: IP resolved for 149.154.175.50
(10:45:32) proxy: Attempting connection to 149.154.175.50
(10:45:32) proxy: Connecting to 149.154.175.50:443 with no proxy
(10:45:32) proxy: Connection in progress
(10:45:32) dnsquery: IP resolved for 149.154.167.51
(10:45:32) proxy: Attempting connection to 149.154.167.51
(10:45:32) proxy: Connecting to 149.154.167.51:443 with no proxy
(10:45:32) proxy: Connection in progress
(10:45:32) dnsquery: IP resolved for 149.154.175.100
(10:45:32) proxy: Attempting connection to 149.154.175.100
(10:45:32) proxy: Connecting to 149.154.175.100:443 with no proxy
(10:45:32) proxy: Connection in progress
(10:45:32) dnsquery: IP resolved for 149.154.167.91
(10:45:32) proxy: Attempting connection to 149.154.167.91
(10:45:32) proxy: Connecting to 149.154.167.91:443 with no proxy
(10:45:32) proxy: Connection in progress
(10:45:32) dnsquery: IP resolved for 149.154.171.5
(10:45:32) proxy: Attempting connection to 149.154.171.5
(10:45:32) proxy: Connecting to 149.154.171.5:443 with no proxy
(10:45:32) proxy: Connection in progress
(10:45:32) proxy: Connecting to 149.154.175.50:443.
(10:45:32) proxy: Connected to 149.154.175.50:443.
(10:45:32) prpl-telegram: outbound rpc connection from dc #1 becomed ready
(10:45:32) proxy: Connecting to 149.154.167.51:443.
(10:45:32) proxy: Connected to 149.154.167.51:443.
(10:45:32) proxy: Connecting to 149.154.167.91:443.
(10:45:32) proxy: Connected to 149.154.167.91:443.
(10:45:32) proxy: Connecting to 149.154.171.5:443.
(10:45:32) proxy: Connected to 149.154.171.5:443.
(10:45:32) prpl-telegram: outbound rpc connection from dc #2 becomed ready
(10:45:32) prpl-telegram: outbound rpc connection from dc #5 becomed ready
(10:45:32) prpl-telegram: outbound rpc connection from dc #4 becomed ready
(10:45:32) proxy: Connecting to 149.154.175.100:443.
(10:45:32) proxy: Connected to 149.154.175.100:443.
(10:45:32) prpl-telegram: outbound rpc connection from dc #3 becomed ready
(10:45:34) util: Writing file accounts.xml to directory C:\Users\XXXXXXX\AppData\Roaming\.purple
(10:45:34) util: Writing file C:\Users\XXXXXXX\AppData\Roaming\.purple\accounts.xml
(10:45:36) prefs: /pidgin/filelocations/last_save_folder changed, scheduling save.

**Comment by ralpheeee88** [comment]
(https://wiki.archlinux.org/index.php/WeeChat) telegram keeps disconnecting and reconnecting:(...when ever i post a message it disconnects. will install the git version
