### ISSUE TITLE
Crash upon login (app launch)

### ISSUE THREAD

**Issue by nemobis** [majn/telegram-purple#335]
With Pidgin 2.11.0-1.fc25 and purple-telegram-1.3.0-1.fc25.x86_64, I successfully enabled my Telegram account and I see some contacts in the "buddy list", but the application crashes after few instants.

With `pidgin -d`, I see this happens during the process of fetching and creating the list of contacts:
```
(10:10:43) g_log: (tgp-blist.c:44):tgp_blist_lookup_purple_name: runtime check failed: (name)
(10:10:43) prpl-telegram: Adding contact '(null)' to buddy list
(10:10:43) g_log: (tgp-blist.c:44):tgp_blist_lookup_purple_name: runtime check failed: (name)
(10:10:43) g_log: purple_buddy_new: assertion 'name != NULL' failed
(10:10:43) g_log: purple_blist_node_set_int: assertion 'node != NULL' failed
(10:10:43) g_log: purple_blist_node_set_int: assertion 'node != NULL' failed
(10:10:43) g_log: purple_blist_add_buddy: assertion 'buddy != NULL' failed
(10:10:43) g_log: purple_blist_node_get_string: assertion 'node != NULL' failed
(10:10:43) g_log: purple_blist_node_get_type: assertion 'node != NULL' failed
(10:10:43) g_log: purple_blist_node_get_type: assertion 'node != NULL' failed
```
(more: https://gist.github.com/nemobis/6ce9b446d72043ae96a1e0a4640b4b82 )

**Comment by MaksVal** [comment]
Hi!

I have a similar problem. I try to initialize my account of telegram in to the pidgin's program.
The pidgin was crashed:
`Breakpoint 1, tgp_info_update_photo (node=0x0, P=0x1d795a0) at tgp-info.c:80
    80          tgl_do_load_file_location (pbn_get_data (node)->TLS, &P->user.photo_big, tgp_info_load_photo_done, P);`

    #0  0x00007fffdc51e670 in tgp_info_update_photo (node=<optimized out>, P=0x1c78000) at tgp-info.c:80
    #1  0x00007fffdc51ddad in tgp_blist_contact_add (TLS=TLS@entry=0x1ade520, U=0x1c78000) at tgp-blist.c:165
    #2  0x00007fffdc51647f in on_get_dialog_list_done (TLS=0x1ade520, extra=<optimized out>, success=1, size=<optimized out>, peers=<optimized out>, last_msg_id=<optimized out>, unread_count=0xbc1db0)
    at telegram-purple.c:256
    #3  0x00007fffdc527873 in get_dialogs_on_answer (TLS=0x1ade520, q=0x1b253c0, D=0x1c84820) at queries.c:1750
    #4  0x00007fffdc52a05f in tglq_query_result (TLS=TLS@entry=0x1ade520, id=<optimized out>) at queries.c:479
    #5  0x00007fffdc521a9f in work_rpc_result (c=0x7fffdd82b4b4 <Response.11334+10356>, msg_id=<optimized out>, TLS=0x1ade520) at mtproto-client.c:848
    #6  rpc_execute_answer (TLS=TLS@entry=0x1ade520, c=0x7fffdd82b4b4 <Response.11334+10356>, c@entry=0xb5bad0, msg_id=<optimized out>) at mtproto-client.c:949
    #7  0x00007fffdc522c1e in process_rpc_message (enc=0x7fffdd828c40 <Response.11334>, len=<optimized out>, c=0xb5bad0, TLS=0x1ade520) at mtproto-client.c:1135
    #8  rpc_execute (TLS=0x1ade520, c=0xb5bad0, op=<optimized out>, len=<optimized out>) at mtproto-client.c:1189
    #9  0x00007fffdc511db0 in try_rpc_read (c=0xb5bad0) at tgp-net.c:431
    #10 try_read (c=0xb5bad0) at tgp-net.c:476
    #11 conn_try_read (arg=0xb5bad0, source=<optimized out>, cond=cond@entry=PURPLE_INPUT_READ) at tgp-net.c:227
    #12 0x00000000004698be in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x1b13650) at gtkeventloop.c:73
    #13 0x00007ffff51dfc6d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
    #14 0x00007ffff51e0040 in g_main_context_iterate.isra () from /usr/lib64/libglib-2.0.so.0

 
This problem still alive if I have a blank contact(a chat). I removed a blank contact(or a private chat) and then the pidgin is working fine.
why don't you check the contents of a variable?


Thanks!

**Comment by nemobis** [comment]
A comment by another person was deleted and mentioned a blank chat derived from a secret chat. I confirm I have some secret chats on my phone and at least one contact (which I had redacted from the gist) which might have had a blank display name.

**Comment by MaksVal** [comment]
May be a similar: #349
