### ISSUE TITLE
Pidgin was crashed if a contact contain of blank name 

### ISSUE THREAD

**Issue by MaksVal** [majn/telegram-purple#349]
Hi!

I have a similar problem. I try to initialize my account of telegram in to the pidgin's program.
The pidgin was crashed:
`Breakpoint 1, tgp_info_update_photo (node=0x0, P=0x1d795a0) at tgp-info.c:80
    80          tgl_do_load_file_location (pbn_get_data (node)->TLS, &P->user.photo_big, tgp_info_load_photo_done, P);`

    #0  0x00007fffdc51e670 in tgp_info_update_photo (node=<optimized out>, P=0x1c78000) at tgp-info.c:80
    #1  0x00007fffdc51ddad in tgp_blist_contact_add (TLS=TLS@entry=0x1ade520, U=0x1c78000) at tgp-blist.c:165
    #2  0x00007fffdc51647f in on_get_dialog_list_done (TLS=0x1ade520, extra=<optimized out>, success=1, size=<optimized out>, peers=<optimized out>, last_msg_id=<optimized out>, unread_count=0xbc1db0)
    at telegram-purple.c:256
    #3  0x00007fffdc527873 in get_dialogs_on_answer (TLS=0x1ade520, q=0x1b253c0, D=0x1c84820) at queries.c:1750
    #4  0x00007fffdc52a05f in tglq_query_result (TLS=TLS@entry=0x1ade520, id=<optimized out>) at queries.c:479
    #5  0x00007fffdc521a9f in work_rpc_result (c=0x7fffdd82b4b4 <Response.11334+10356>, msg_id=<optimized out>, TLS=0x1ade520) at mtproto-client.c:848
    #6  rpc_execute_answer (TLS=TLS@entry=0x1ade520, c=0x7fffdd82b4b4 <Response.11334+10356>, c@entry=0xb5bad0, msg_id=<optimized out>) at mtproto-client.c:949
    #7  0x00007fffdc522c1e in process_rpc_message (enc=0x7fffdd828c40 <Response.11334>, len=<optimized out>, c=0xb5bad0, TLS=0x1ade520) at mtproto-client.c:1135
    #8  rpc_execute (TLS=0x1ade520, c=0xb5bad0, op=<optimized out>, len=<optimized out>) at mtproto-client.c:1189
    #9  0x00007fffdc511db0 in try_rpc_read (c=0xb5bad0) at tgp-net.c:431
    #10 try_read (c=0xb5bad0) at tgp-net.c:476
    #11 conn_try_read (arg=0xb5bad0, source=<optimized out>, cond=cond@entry=PURPLE_INPUT_READ) at tgp-net.c:227
    #12 0x00000000004698be in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x1b13650) at gtkeventloop.c:73
    #13 0x00007ffff51dfc6d in g_main_context_dispatch () from /usr/lib64/libglib-2.0.so.0
    #14 0x00007ffff51e0040 in g_main_context_iterate.isra () from /usr/lib64/libglib-2.0.so.0

This problem still alive if I have a blank contact(a chat). I removed a blank contact(or a private chat) and then the pidgin is working fine.
why don't you check the contents of a variable?

Thanks!

PS
The problem contact isn't have name or username. It have only a phone number.
I removed contact and add:

> diff --git a/tgp-blist.c b/tgp-blist.c
> index 49379da..12aee7e 100644
> --- a/tgp-blist.c
> +++ b/tgp-blist.c
> @@ -154,15 +154,16 @@ PurpleBuddy *tgp_blist_buddy_find (struct tgl_state *TLS, tgl_peer_id_t user) {
>  
>  void tgp_blist_contact_add (struct tgl_state *TLS, struct tgl_user *U) {
>    PurpleBuddy *buddy = tgp_blist_buddy_find (TLS, U->id);
> -  
> +
>    if (! buddy) {
>      tgl_peer_t *P = tgl_peer_get (TLS, U->id);
> -    
> +
>      info ("Adding contact '%s' to buddy list", tgp_blist_lookup_purple_name (TLS, U->id));
>      buddy = tgp_blist_buddy_new (TLS, P);
>      purple_blist_add_buddy (buddy, NULL, tgp_blist_group_init (_("Telegram")), NULL);
> -    
> -    tgp_info_update_photo (&buddy->node, P);
> +
> +    if (&buddy->node)
> +     tgp_info_update_photo (&buddy->node, P);
>    }
>    p2tgl_prpl_got_user_status (TLS, U->id, &U->status);
>  }
>

**Comment by Strykar** [comment]
Any update/timeline on this?
