### ISSUE TITLE
Crash on opening a chat on reconnect

### ISSUE THREAD

**Issue by bodqhrohro** [majn/telegram-purple#537]
```
(12:55:20) log: Failed to open log file "/home/bodqhrohro/.purple/logs/minetest@ttyh.log" for reading: Нет такого файла или каталога
(12:55:20) Gtk: IA__gtk_widget_hide: assertion 'GTK_IS_WIDGET (widget)' failed
(12:55:20) prpl-telegram: tgp_chat_add_all_users()
(12:55:20) prpl-telegram: sending all pending recipes
(12:55:20) prpl-telegram: tgl_do_mark_read (1233111512)
(12:55:20) prpl-telegram: tgp_msg_process_in_ready, queue size=1
(12:55:20) prpl-telegram: sending all pending recipes
(12:55:20) prpl-telegram: tgl_do_mark_read (1233111512)
(12:55:20) prpl-telegram: tgp_msg_process_in_ready, queue size=0
(12:55:20) prpl-telegram: tgp_channel_load_admins_done()
(12:55:20) discord: got frame data: {"t":"GUILD_MEMBER_LIST_UPDATE","s":44,"op":0,"d":{"ops":[{"op":"UPDATE","item":{"member":{"user":{"username":"harmony","public_flags":768,"id":"89528058242945024","discriminator":"6666","avatar":"dddbad3cc0458ea842d64a47e5aec419"},"roles":[],"presence":{"user":{"id":"89528058242945024"},"status":"dnd","game":{"type":4,"name":"Custom Status","id":"custom","flags":0,"emoji":{"name":"goose","id":"627243998645321797","animated":true},"created_at":1586685318961},"client_status":{"mobile":"dnd"},"activities":[{"type":4,"name":"Custom Status","id":"custom","flags":0,"emoji":{"name":"goose","id":"627243998645321797","animated":true},"created_at":1586685318961}]},"mute":false,"joined_at":"2016-12-26T18:57:06.465000+00:00","hoisted_role":null,"deaf":false}},"index":86}],"online_count":293,"member_count":6173,"id":"everyone","guild_id":"226791405589233664","groups":[{"id":"226792247637573632","count":2},{"id":"226792438570680320","count":4},{"id":"online","count":269}]}}
(12:55:20) discord: sending frame: {"op":1,"d":44}
(12:55:20) log: Failed to open log file "/home/bodqhrohro/.purple/logs/minetest@ttyh.log" for reading: Нет такого файла или каталога

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
g_slist_find (list=0x31 = {...}, data=data@entry=0x5555568360e0) at ../../../glib/gslist.c:695
695	../../../glib/gslist.c: Нет такого файла или каталога.
@(gdb) bt
#0  0x00007ffff72aaf78 in g_slist_find (list=0x31 = {...}, data=data@entry=0x5555568360e0) at ../../../glib/gslist.c:695
#1  0x00007ffff718c0eb in serv_got_joined_chat (gc=0x55555b4b1160, id=id@entry=1233111512, name=name@entry=0x555558da7900 "\320^\t[UU")
    at ././libpurple/server.c:861
#2  0x00007fffe94cb809 in tgp_chat_show (TLS=TLS@entry=0x55555b8d5840, P=P@entry=0x55555eb9ae00) at ./tgl/tgl.h:323
#3  0x00007fffe94c9bd5 in tgp_chat_got_in
    (TLS=TLS@entry=0x55555b8d5840, chat=0x55555eb9ae00, from=..., message=message@entry=0x55555bcd7630 "&lt;nekorin&gt; ого, у меня вагонетка не лагает", flags=2, when=1586677474) at tgp-2prpl.c:86
#4  0x00007fffe94ce368 in tgp_msg_display (C=0x55555aceb080, TLS=0x55555b8d5840) at tgp-msg.c:839
#5  0x00007fffe94ce368 in tgp_msg_process_in_ready (TLS=0x55555b8d5840) at tgp-msg.c:881
#6  0x00007fffe94cacbb in tgp_channel_load_finish (TLS=0x55555b8d5840, D=0x555556314e10, success=1) at tgp-chat.c:519
#7  0x00007fffe94e5d22 in channels_get_members_on_answer (TLS=0x55555b8d5840, q=0x55555db06b10, D=0x555558c377c0) at queries.c:2898
#8  0x00007fffe94ddd0c in tglq_query_result (TLS=TLS@entry=0x55555b8d5840, id=<optimized out>) at queries.c:479
#9  0x00007fffe94d5a96 in work_rpc_result (c=0x55555f0e5710, msg_id=<optimized out>, TLS=0x55555b8d5840) at mtproto-client.c:848
#10 0x00007fffe94d5a96 in rpc_execute_answer (TLS=TLS@entry=0x55555b8d5840, c=c@entry=0x55555f0e5710, msg_id=<optimized out>)
    at mtproto-client.c:949
#11 0x00007fffe94d6a00 in process_rpc_message (enc=0x7fffea5cfcc0 <Response.11285>, len=<optimized out>, c=0x55555f0e5710, TLS=0x55555b8d5840)
    at mtproto-client.c:1135
#12 0x00007fffe94d6a00 in rpc_execute (TLS=0x55555b8d5840, c=0x55555f0e5710, op=<optimized out>, len=<optimized out>) at mtproto-client.c:1189
@--Type <RET> for more, q to quit, c to continue without paging--
#13 0x00007fffe94c46d9 in try_rpc_read (c=0x55555f0e5710) at tgp-net.c:431
#14 0x00007fffe94c46d9 in try_read (c=0x55555f0e5710) at tgp-net.c:476
#15 0x00007fffe94c46d9 in conn_try_read (arg=0x55555f0e5710, source=<optimized out>, cond=cond@entry=PURPLE_INPUT_READ) at tgp-net.c:227
#16 0x00005555555cb1e2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x555559e67b10)
    at ././pidgin/gtkeventloop.c:73
#17 0x00007ffff728bdfe in g_main_dispatch (context=0x555555684800) at ../../../glib/gmain.c:3216
#18 0x00007ffff728bdfe in g_main_context_dispatch (context=context@entry=0x555555684800) at ../../../glib/gmain.c:3881
#19 0x00007ffff728c1b0 in g_main_context_iterate (context=0x555555684800, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:3954
#20 0x00007ffff728c483 in g_main_loop_run (loop=0x55555678de50) at ../../../glib/gmain.c:4148
#21 0x00007ffff776212a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#22 0x0000555555590970 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:939
```
The chat had to be opened because of the new incoming message, and something went wrong.

It's also strange that it was trying to look for the log directory in `~/.purple/logs/` first rather than in `~/.purple/logs/telegram/`. Is that expected?

**Comment by IgorCharlie** [comment]
Me too
