### ISSUE TITLE
SIGFPE in tgp_chat_add_all_users()

### ISSUE THREAD

**Issue by bodqhrohro** [majn/telegram-purple#566]
```
(13:47:55) prpl-telegram: tgp_chat_add_all_users()
(13:47:55) g_log: file tgp-chat.c: line 167 (tgp_chat_add_all_users): should not be reached

Thread 1 "pidgin" received signal SIGFPE, Arithmetic exception.
0x00007ffff7261b38 in ?? ()
@(gdb) bt
#0  0x00007ffff7261b38 in ?? ()
#1  0x0000000063e07450 in ?? ()
#2  0x000055555787ac00 in ?? ()
#3  0x00000000602acb28 in ?? ()
#4  0x0000555557eafcf0 in ?? ()
#5  0x000055555787ac00 in ?? ()
#6  0x0000000063e07450 in ?? ()
#7  0x000055555802dca0 in ?? ()
#8  0x63e0745000000001 in ?? ()
#9  0x00000000602acb28 in ?? ()
#10 0x00007fffe87fa2d1 in ?? ()
#11 0x000055555802dca0 in ?? ()
#12 0x63e0745000000001 in ?? ()
#13 0x0000000000000006 in ?? ()
#14 0x00007fffe87f2bf3 in ?? ()
#15 0x57dad00000000005 in ?? ()
#16 0xd61ace4c6a8de342 in ?? ()
#17 0x0000555555cb4f80 in ?? ()
#18 0x0000555556a10d10 in ?? ()
@--Type <RET> for more, q to quit, c to continue without paging--
#19 0x0000555556a6a0a0 in ?? ()
#20 0x000055555787ac00 in ?? ()
#21 0x000055555802dca0 in ?? ()
#22 0x0000000000000001 in ?? ()
#23 0x0000555556700c00 in ?? ()
#24 0x00007fffe87f7368 in ?? ()
#25 0x00000000602acb28 in ?? ()
#26 0x00007fffe87f7328 in ?? ()
#27 0x00007fffffffb6d0 in ?? ()
#28 0x00007fffffffb6cc in ?? ()
#29 0x0000000000000000 in ?? ()
@(gdb) 
```

**Comment by bodqhrohro** [comment]
And on the next run:
```
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgl_do_mark_read (1289232687)
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=38
(14:48:25) LaTeX: Writing Message: En megyek plázázni ma
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgl_do_mark_read (1289232687)
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=37
(14:48:25) LaTeX: Writing Message: 😆😆😆
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgl_do_mark_read (1289232687)
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
(14:48:25) prpl-telegram: sending all pending recipes
(14:48:25) prpl-telegram: tgp_msg_process_in_ready, queue size=36
pidgin: mtproto-common.h:329: fetch_long: Проверочное утверждение «in_ptr + 2 <= in_end» не выполнено.

Thread 1 "pidgin" received signal SIGABRT, Aborted.
0x00007ffff6deddb1 in ?? ()
@(gdb) bt
#0  0x00007ffff6deddb1 in ?? ()
#1  0x0000000000000000 in ?? ()
```

**Comment by bodqhrohro** [comment]
Another SIGFPE:
```
(00:31:44) log: Failed to open log file "/home/bodqhrohro/.purple/logs/Stickers.log" for reading: Нет такого файла или каталога
@--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "pidgin" received signal SIGFPE, Arithmetic exception.
0x00007ffff72e199c in g_hash_table_hash_to_index (hash=429000, hash_table=0x555556204640 = {...}) at ../../../glib/ghash.c:434
434	../../../glib/ghash.c: Нет такого файла или каталога.
@(gdb) bt
#0  0x00007ffff72e199c in g_hash_table_hash_to_index (hash=429000, hash_table=0x555556204640 = {...}) at ../../../glib/ghash.c:434
#1  g_hash_table_lookup_node (hash_return=<synthetic pointer>, key=0x68bc8, hash_table=0x555556204640 = {...}) at ../../../glib/ghash.c:478
#2  g_hash_table_lookup (hash_table=0x555556204640 = {...}, key=key@entry=0x68bc8) at ../../../glib/ghash.c:1511
#3  0x00007fffdb3a74e0 in tgp_blist_lookup_purple_name (TLS=TLS@entry=0x5555578cb800, id=...) at tgp-blist.c:42
#4  0x00007fffdb39ff00 in p2tgl_got_im_combo (TLS=0x5555578cb800, who=..., msg=0x5555580c3b30 "/stats", flags=1025, when=1649712673)
    at tgp-2prpl.c:123
#5  0x00007fffdb3a48f9 in tgp_msg_display (C=0x555555dfea80, TLS=0x5555578cb800) at tgp-msg.c:887
#6  tgp_msg_process_in_ready (TLS=0x5555578cb800) at tgp-msg.c:911
#7  0x00007fffdb3b666c in download_on_error
    (TLS=0x5555578cb800, q=0x555557fe8fb0, error_code=<optimized out>, error_len=<optimized out>, error=<optimized out>) at queries.c:3287
#8  0x00007fffdb3c186e in tglq_query_error (TLS=0x5555578cb800, id=<optimized out>) at queries.c:415
#9  0x00007fffdb3ac8f3 in work_rpc_result (c=0x555557ed5830, msg_id=<optimized out>, TLS=0x5555578cb800) at mtproto-client.c:846
#10 0x00007fffdb3ad8f0 in process_rpc_message (enc=0x7fffdc4adcc0 <Response.43>, len=<optimized out>, c=0x555557ed5830, TLS=0x5555578cb800)
    at mtproto-client.c:1135
#11 rpc_execute (TLS=0x5555578cb800, c=0x555557ed5830, op=<optimized out>, len=<optimized out>) at mtproto-client.c:1189
#12 0x00007fffdb39aae9 in try_rpc_read (c=0x555557ed5830) at tgp-net.c:431
#13 try_read (c=<optimized out>) at tgp-net.c:476
#14 conn_try_read (arg=0x555557ed5830, source=<optimized out>, cond=cond@entry=PURPLE_INPUT_READ) at tgp-net.c:227
#15 0x00005555555cdfb2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x555557f9ea20) at ././pidgin/gtkeventloop.c:73
@--Type <RET> for more, q to quit, c to continue without paging--
#16 0x00007ffff72f4be4 in g_main_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:3381
#17 g_main_context_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:4099
#18 0x00007ffff72f4f88 in g_main_context_iterate
    (context=context@entry=0x5555556c8b10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../../../glib/gmain.c:4175
#19 0x00007ffff72f503f in g_main_context_iteration (context=0x5555556c8b10, may_block=1) at ../../../glib/gmain.c:4240
#20 0x00007ffff79d7d91 in gtk_main_iteration () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#21 0x00007ffff13d5655 in conversation_created_cb (conv=<optimized out>) at plugin.c:91
#22 0x00007ffff70ad81c in purple_signal_emit_vargs
    (instance=<optimized out>, signal=signal@entry=0x7ffff71003f4 "conversation-created", args=args@entry=0x7fffffffb200)
    at ././libpurple/signals.c:482
#23 0x00007ffff70ad9ae in purple_signal_emit (instance=<optimized out>, signal=signal@entry=0x7ffff71003f4 "conversation-created")
    at ././libpurple/signals.c:434
#24 0x00007ffff70766dc in purple_conversation_new
    (type=type@entry=PURPLE_CONV_TYPE_CHAT, account=account@entry=0x555555c11ae0, name=name@entry=0x555557efcfa0 "\200\321\030VUU")
    at ././libpurple/conversation.c:497
#25 0x00007ffff70ac86c in serv_got_joined_chat (gc=0x555557506f80, id=id@entry=1279877202, name=name@entry=0x555557efcfa0 "\200\321\030VUU")
    at ././libpurple/server.c:856
#26 0x00007fffdb3a1989 in tgp_chat_show (TLS=TLS@entry=0x5555578cb800, P=P@entry=0x555555874000) at ./tgl/tgl.h:323
#27 0x00007fffdb39fd45 in tgp_chat_got_in
@--Type <RET> for more, q to quit, c to continue without paging--
    (TLS=TLS@entry=0x5555578cb800, chat=0x555555874000, from=..., message=message@entry=0x555557ef2060 "Unsupported User добавил пользователя Unsupported User.", flags=6, when=1649712658) at tgp-2prpl.c:86
#28 0x00007fffdb3a4aca in tgp_msg_display (C=0x555557b3e460, TLS=0x5555578cb800) at tgp-msg.c:872
#29 tgp_msg_process_in_ready (TLS=0x5555578cb800) at tgp-msg.c:911
#30 0x00007fffdb3a0e3b in tgp_channel_load_finish (TLS=0x5555578cb800, D=0x555557b3e490, success=1) at tgp-chat.c:519
#31 0x00007fffdb3bdbb2 in channels_get_members_on_answer (TLS=0x5555578cb800, q=0x555556f922f0, D=0x555557508910) at queries.c:2898
#32 0x00007fffdb3b587e in tglq_query_result (TLS=TLS@entry=0x5555578cb800, id=<optimized out>) at queries.c:479
#33 0x00007fffdb3ac5bc in work_rpc_result (c=0x555557efc670, msg_id=<optimized out>, TLS=0x5555578cb800) at mtproto-client.c:848
#34 0x00007fffdb3ad8f0 in process_rpc_message (enc=0x7fffdc4adcc0 <Response.43>, len=<optimized out>, c=0x555557efc670, TLS=0x5555578cb800)
    at mtproto-client.c:1135
#35 rpc_execute (TLS=0x5555578cb800, c=0x555557efc670, op=<optimized out>, len=<optimized out>) at mtproto-client.c:1189
#36 0x00007fffdb39aae9 in try_rpc_read (c=0x555557efc670) at tgp-net.c:431
#37 try_read (c=<optimized out>) at tgp-net.c:476
#38 conn_try_read (arg=0x555557efc670, source=<optimized out>, cond=cond@entry=PURPLE_INPUT_READ) at tgp-net.c:227
#39 0x00005555555cdfb2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x5555574e4430) at ././pidgin/gtkeventloop.c:73
#40 0x00007ffff72f4be4 in g_main_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:3381
#41 g_main_context_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:4099
#42 0x00007ffff72f4f88 in g_main_context_iterate (context=0x5555556c8b10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4175
@--Type <RET> for more, q to quit, c to continue without paging--
#43 0x00007ffff72f5273 in g_main_loop_run (loop=0x555555ec8160) at ../../../glib/gmain.c:4373
#44 0x00007ffff79d7b2a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#45 0x0000555555591d70 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:947
```
