### ISSUE TITLE
A crash that shoudln't have happened

### ISSUE THREAD

**Issue by bodqhrohro** [majn/telegram-purple#571]
When I re-joined a group chat:
```
Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
g_slist_find (list=0x31 = {...}, data=data@entry=0x555559b8ed60) at ../../../glib/gslist.c:716
716	../../../glib/gslist.c: Нет такого файла или каталога.
@(gdb) bt
#0  g_slist_find (list=0x31 = {...}, data=data@entry=0x555559b8ed60) at ../../../glib/gslist.c:716
#1  0x00007ffff70bab7f in serv_got_joined_chat
    (gc=0x555557c47940, id=id@entry=1191514474, name=name@entry=0x55555ad83c20 "bodqhrohro@irc.gnome.org (IRC)") at ././libpurple/server.c:861
#2  0x00007fffdb3a9809 in tgp_chat_show (TLS=TLS@entry=0x55555a3dec00, P=P@entry=0x55555bf0c030) at ./tgl/tgl.h:323
#3  0x00007fffdb3a7bd5 in tgp_chat_got_in
    (TLS=TLS@entry=0x55555a3dec00, chat=0x55555bf0c030, from=..., message=message@entry=0x555559f49450 "Bohdan Horbeshko добавил пользователя Bohdan Horbeshko.", flags=5, when=1623328525) at tgp-2prpl.c:86
#4  0x00007fffdb3ac368 in tgp_msg_display (C=0x55555b71a560, TLS=0x55555a3dec00) at tgp-msg.c:842
#5  tgp_msg_process_in_ready (TLS=0x55555a3dec00) at tgp-msg.c:881
#6  0x00007fffdb3a8cbb in tgp_channel_load_finish (TLS=0x55555a3dec00, D=0x55555611c170, success=1) at tgp-chat.c:519
#7  0x00007fffdb3c3d22 in channels_get_members_on_answer (TLS=0x55555a3dec00, q=0x55555b4a9030, D=0x555558c0cd80) at queries.c:2898
#8  0x00007fffdb3bbd0c in tglq_query_result (TLS=TLS@entry=0x55555a3dec00, id=<optimized out>) at queries.c:479
#9  0x00007fffdb3b3a96 in work_rpc_result (c=0x55555a7bc330, msg_id=<optimized out>, TLS=0x55555a3dec00) at mtproto-client.c:848
#10 0x00007fffdb3b3be7 in work_container (msg_id=<optimized out>, c=0x55555a7bc330, TLS=0x55555a3dec00) at mtproto-client.c:800
#11 rpc_execute_answer (TLS=TLS@entry=0x55555a3dec00, c=c@entry=0x55555a7bc330, msg_id=<optimized out>) at mtproto-client.c:943
#12 0x00007fffdb3b4a00 in process_rpc_message (enc=0x7fffdc4adcc0 <Response.11285>, len=<optimized out>, c=0x55555a7bc330, TLS=0x55555a3dec00)
    at mtproto-client.c:1135
#13 rpc_execute (TLS=0x55555a3dec00, c=0x55555a7bc330, op=<optimized out>, len=<optimized out>) at mtproto-client.c:1189
#14 0x00007fffdb3a26d9 in try_rpc_read (c=0x55555a7bc330) at tgp-net.c:431
@--Type <RET> for more, q to quit, c to continue without paging--
#15 try_read (c=0x55555a7bc330) at tgp-net.c:476
#16 conn_try_read (arg=0x55555a7bc330, source=<optimized out>, cond=cond@entry=PURPLE_INPUT_READ) at tgp-net.c:227
#17 0x00005555555ce0e2 in pidgin_io_invoke (source=<optimized out>, condition=<optimized out>, data=0x55555a0fef10) at ././pidgin/gtkeventloop.c:73
#18 0x00007ffff71bcd6f in g_main_dispatch (context=0x5555556b3ed0) at ../../../glib/gmain.c:3325
#19 g_main_context_dispatch (context=0x5555556b3ed0) at ../../../glib/gmain.c:4043
#20 0x00007ffff71bd118 in g_main_context_iterate (context=0x5555556b3ed0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4119
#21 0x00007ffff71bd40b in g_main_loop_run (loop=0x5555579d2070) at ../../../glib/gmain.c:4317
#22 0x00007ffff788db2a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#23 0x0000555555591d81 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:947
```
What does that IRC account do here? It wasn't even enabled for months (or even years, as I dropped using the Pidgin's buggy IRC prpl a long time ago). Looks like a severe memory corruption issue, maybe not even in the telegram-purple itself.

**Comment by BenWiederhake** [comment]
Side note: Since telegram-purple does some weird memory-overflowy things, I wouldn't be too surprised if it turns out that this is due to telegram-purple afterall.

**Comment by EionRobb** [comment]
@bodqhrohro what version of pidgin are you using?

**Comment by bodqhrohro** [comment]
@EionRobb Pidgin 2.14.1 (libpurple 2.14.1)
f902de8a1b5eac32c33c63c95b40693ba5c4aed8
