### ISSUE TITLE
SIGSEGV in tgp_g_list_free_full

### ISSUE THREAD

**Issue by bodqhrohro** [majn/telegram-purple#579]
```
(08:31:09) connection: Destroying connection 0x55555c627db0
(08:31:09) account: Disconnecting account 380········· (0x555555d0d4b0)
(08:31:09) connection: Disconnecting connection 0x55555a01e330
(08:31:09) prpl-telegram: tgprpl_close()

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x55565a3366a0) at malloc.c:3122
3122	malloc.c: Нет такого файла или каталога.
@(gdb) dns[2130017]: nobody needs me... =(
dns[2130021]: nobody needs me... =(
dns[2129998]: nobody needs me... =(
dns[2130014]: nobody needs me... =(
bt
#0  __GI___libc_free (mem=0x55565a3366a0) at malloc.c:3122
#1  0x00007ffff72e9758 in g_list_foreach (list=<optimized out>, 
    list@entry=0x55555ba8cce0 = {...}, func=0x7ffff72f3e90 <g_free>, user_data=user_data@entry=0x0) at ../../../glib/glist.c:1090
#2  0x00007ffff72e977b in g_list_free_full (list=0x55555ba8cce0 = {...}, free_func=<optimized out>) at ../../../glib/glist.c:244
#3  0x00007fffdb3a0c8a in tgp_g_list_free_full (list=<optimized out>, free_func=<optimized out>) at tgp-utils.c:98
#4  0x00007fffdb3a0a38 in connection_data_free (conn=0x55555ab7fd40) at tgp-structs.c:123
#5  0x00007ffff706ad6a in _purple_connection_destroy (gc=0x55555a01e330) at ././libpurple/connection.c:275
#6  0x00007ffff7056e6e in purple_account_disconnect (account=account@entry=0x555555d0d4b0) at ././libpurple/account.c:1339
#7  0x00005555555b1a63 in pidgin_connection_network_disconnected () at ././pidgin/gtkconn.c:200
#8  0x00007ffff62f19da in  () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#9  0x00007ffff62f0b21 in  () at /usr/lib/x86_64-linux-gnu/libffi.so.8
#10 0x00007ffff73e2eec in g_cclosure_marshal_generic
    (closure=0x5555567ef790, return_gvalue=0x0, n_param_values=<optimized out>, param_values=<optimized out>, invocation_hint=<optimized out>, marshal_data=<optimized out>) at ../../../gobject/gclosure.c:1534
#11 0x00007ffff625a209 in  () at /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
#15 0x00007ffff73fb4ff in <emit signal received:org-freedesktop-NetworkManager-StateChanged on instance 0x555555d19530 [DBusGProxy]>
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>) at ../../../gobject/gsignal.c:3553
    #12 0x00007ffff73e26df in g_closure_invoke
    (closure=0x5555567ef790, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fffffffb3a0, invocation_hint=in@--Type <RET> for more, q to quit, c to continue without paging--
vocation_hint@entry=0x7fffffffb320) at ../../../gobject/gclosure.c:830
    #13 0x00007ffff73f4b36 in signal_emit_unlocked_R
    (node=node@entry=0x5555567f05c0, detail=detail@entry=3614, instance=instance@entry=0x555555d19530, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffffffb3a0) at ../../../gobject/gsignal.c:3742
    #14 0x00007ffff73faf51 in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffffffb550)
    at ../../../gobject/gsignal.c:3497
#16 0x00007ffff625ab12 in  () at /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
#17 0x00007ffff7f4a8c5 in dbus_connection_dispatch () at /lib/x86_64-linux-gnu/libdbus-1.so.3
#18 0x00007ffff6267095 in  () at /usr/lib/x86_64-linux-gnu/libdbus-glib-1.so.2
#19 0x00007ffff72edc7b in g_main_dispatch (context=0x5555556c8710) at ../../../glib/gmain.c:3381
#20 g_main_context_dispatch (context=0x5555556c8710) at ../../../glib/gmain.c:4099
#21 0x00007ffff72edf28 in g_main_context_iterate (context=0x5555556c8710, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4175
#22 0x00007ffff72ee213 in g_main_loop_run (loop=0x55555791f900) at ../../../glib/gmain.c:4373
#23 0x00007ffff79d0b2a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#24 0x0000555555591d70 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:947
```

**Comment by bodqhrohro** [comment]
```
(12:17:17) connection: Disconnecting connection 0x555555d36780
(12:17:17) prpl-telegram: tgprpl_close()

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
0x00007ffff6d70945 in __GI___libc_free (mem=0x555655d36830) at malloc.c:3288
3288	malloc.c: Нет такого файла или каталога.
@(gdb) dns[879834]: nobody needs me... =(
bt
#0  0x00007ffff6d70945 in __GI___libc_free (mem=0x555655d36830) at malloc.c:3288
#1  0x00007ffff72f07b8 in g_list_foreach (list=<optimized out>, 
    list@entry=0x5555578eb040 = {...}, func=0x7ffff72faef0 <g_free>, user_data=user_data@entry=0x0) at ../../../glib/glist.c:1090
#2  0x00007ffff72f07db in g_list_free_full (list=0x5555578eb040 = {...}, free_func=<optimized out>) at ../../../glib/glist.c:244
#3  0x00007fffdb3a0c8a in tgp_g_list_free_full (list=<optimized out>, free_func=<optimized out>) at tgp-utils.c:98
#4  0x00007fffdb3a0a38 in connection_data_free (conn=0x55555803db50) at tgp-structs.c:123
#5  0x00007ffff7071d6a in _purple_connection_destroy (gc=0x555555d36780) at ././libpurple/connection.c:275
#6  0x00007ffff705de6e in purple_account_disconnect (account=account@entry=0x555555c102e0) at ././libpurple/account.c:1339
#7  0x00007ffff7070f16 in purple_connection_disconnect_cb (data=0x555555c102e0, data@entry=<error reading variable: value has been optimized out>)
    at ././libpurple/connection.c:523
#8  0x00007ffff72f5744 in g_timeout_dispatch (source=0x55555806a1f0, callback=<optimized out>, user_data=<optimized out>)
    at ../../../glib/gmain.c:4933
#9  0x00007ffff72f4be4 in g_main_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:3381
#10 g_main_context_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:4099
#11 0x00007ffff72f4f88 in g_main_context_iterate (context=0x5555556c8b10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4175
#12 0x00007ffff72f5273 in g_main_loop_run (loop=0x5555574920f0) at ../../../glib/gmain.c:4373
#13 0x00007ffff79d7b2a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#14 0x0000555555591d70 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:947
```
