### ISSUE TITLE
Pidgin crashes on startup

### ISSUE THREAD

**Issue by Apanatshka** [majn/telegram-purple#58]
A few days ago pidgin stopped working. It crashes on startup. I believe it has to do with the telegram-purple because pidgin doesn't crash when I disabled the telegram account in `~.purple/accounts.xml`, and does crash as soon as I enable the telegram account after startup.
I've tried deleting the `~/.telegram-purple/<number>/auth` file as suggested in #26 for Adium. That got me a pidgin that starts up and asks for the authentication code. When I give it, the telegram app on my phone reports a new computer connected, then pidgin crashes again. 

Some basic info:
```
$ uname -srm
Linux 3.16.7.7-1-MANJARO x86_64
$ pidgin
Pidgin 2.10.11 has segfaulted and attempted to dump a core file.
This is a bug in the software and has happened through
no fault of your own.

If you can reproduce the crash, please notify the developers
by reporting a bug at:
http://developer.pidgin.im/simpleticket/

Please make sure to specify what you were doing at the time
and post the backtrace from the core file.  If you do not know
how to get the backtrace, please read the instructions at
http://developer.pidgin.im/wiki/GetABacktrace
Aborted (core dumped)
$ gdb pidgin
GNU gdb (GDB) 7.9
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from pidgin...(no debugging symbols found)...done.
(gdb) handle SIGPIPE nostop noprint
Signal        Stop	Print	Pass to program	Description
SIGPIPE       No	No	Yes		Broken pipe
(gdb) run
Starting program: /usr/bin/pidgin 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffc9da1700 (LWP 24289)]
[Thread 0x7fffc9da1700 (LWP 24289) exited]
[New Thread 0x7fffcbfff700 (LWP 24241)]
[New Thread 0x7fffd0f40700 (LWP 24239)]
[New Thread 0x7fffd28b1700 (LWP 24237)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffd87b0330 in p2tgl_strdup_alias () from /usr/lib/purple-2/telegram-purple.so
(gdb) bt full
#0  0x00007fffd87b0330 in p2tgl_strdup_alias () from /usr/lib/purple-2/telegram-purple.so
No symbol table info available.
#1  0x00007fffd87b03a6 in p2tgl_got_joined_chat () from /usr/lib/purple-2/telegram-purple.so
No symbol table info available.
#2  0x00007fffd87b15a3 in chat_show () from /usr/lib/purple-2/telegram-purple.so
No symbol table info available.
#3  0x000000000043a0f9 in ?? ()
No symbol table info available.
#4  0x00007ffff526c823 in purple_marshal_BOOLEAN__POINTER () from /usr/lib/libpurple.so.0
No symbol table info available.
#5  0x00007ffff526b972 in purple_signal_emit_vargs_return_1 () from /usr/lib/libpurple.so.0
No symbol table info available.
#6  0x00007ffff526bace in purple_signal_emit_return_1 () from /usr/lib/libpurple.so.0
No symbol table info available.
#7  0x00007ffff52355f1 in purple_connection_set_state () from /usr/lib/libpurple.so.0
No symbol table info available.
#8  0x00007fffd87b013c in on_ready () from /usr/lib/purple-2/telegram-purple.so
No symbol table info available.
#9  0x00007fffd87ae1a8 in ?? () from /usr/lib/purple-2/telegram-purple.so
No symbol table info available.
#10 0x00007ffff55613c3 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#11 0x00007ffff556091d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#12 0x00007ffff5560cf8 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#13 0x00007ffff5561022 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#14 0x00007ffff6822417 in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
No symbol table info available.
#15 0x0000000000431a1b in main ()
No symbol table info available.
```
Let me know if I provide any other information that'll help.

**Comment by majn** [comment]
It was an issue with automatic chat joining, fixed now in the current master.
