### ISSUE TITLE
SIGSEGV in tglmp_encrypt_send_message

### ISSUE THREAD

**Issue by bodqhrohro** [majn/telegram-purple#584]
```
Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
tglmp_encrypt_send_message (TLS=TLS@entry=0x555557beb600, c=0x555556b7f040, msg=msg@entry=0x7fffdf9bfe60 <__packet_buffer+64>, 
    msg_ints=msg_ints@entry=9, flags=flags@entry=1) at mtproto-client.c:736
736	mtproto-client.c: Нет такого файла или каталога.
@(gdb) bt
#0  tglmp_encrypt_send_message
    (TLS=TLS@entry=0x555557beb600, c=0x555556b7f040, msg=msg@entry=0x7fffdf9bfe60 <__packet_buffer+64>, msg_ints=msg_ints@entry=9, flags=flags@entry=1) at mtproto-client.c:736
#1  0x00007fffdb3b178a in tglq_send_query_ex
    (TLS=TLS@entry=0x555557beb600, DC=0x555556b7f050, ints=9, data=0x7fffdf9bfe60 <__packet_buffer+64>, methods=methods@entry=
    0x7fffdb49c0c0 <download_methods>, extra=extra@entry=0x555558c91400, callback=0x7fffdb3a55a0 <tgp_msg_on_loaded_document>, callback_extra=0x555557ae6f50, flags=0) at queries.c:233
#2  0x00007fffdb3b1965 in tglq_send_query
    (TLS=TLS@entry=0x555557beb600, DC=<optimized out>, ints=<optimized out>, data=<optimized out>, methods=methods@entry=
    0x7fffdb49c0c0 <download_methods>, extra=extra@entry=0x555558c91400, callback=0x7fffdb3a55a0 <tgp_msg_on_loaded_document>, callback_extra=0x555557ae6f50) at queries.c:262
#3  0x00007fffdb3b4911 in download_next_part
    (TLS=TLS@entry=0x555557beb600, D=0x555558c91400, callback=0x7fffdb3a55a0 <tgp_msg_on_loaded_document>, callback_extra=0x555557ae6f50)
    at queries.c:3376
#4  0x00007fffdb3b4b9d in download_retry_alarm (TLS=0x555557beb600, arg=0x5555577af9f0) at queries.c:3261
#5  0x00007fffdb39ad78 in timer_alarm (arg=<error reading variable: value has been optimized out>) at tgp-timers.c:35
#6  0x00007ffff72f6744 in g_timeout_dispatch (source=0x555557aea780, callback=<optimized out>, user_data=<optimized out>)
    at ../../../glib/gmain.c:4933
#7  0x00007ffff72f5be4 in g_main_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:3381
@--Type <RET> for more, q to quit, c to continue without paging--
#8  g_main_context_dispatch (context=0x5555556c8b10) at ../../../glib/gmain.c:4099
#9  0x00007ffff72f5f88 in g_main_context_iterate (context=0x5555556c8b10, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../../../glib/gmain.c:4175
#10 0x00007ffff72f6273 in g_main_loop_run (loop=0x5555564e4fe0) at ../../../glib/gmain.c:4373
#11 0x00007ffff79d8b2a in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#12 0x0000555555591d70 in main (argc=<optimized out>, argv=<optimized out>) at ././pidgin/gtkmain.c:947
```

**Comment by BenWiederhake** [comment]
Thank you for posting all these backtraces. Are you aware that this project is effectively abandoned? Unless you find someone to write a PR (which I'll happily merge), nothing will happen.

**Comment by bodqhrohro** [comment]
> Are you aware that this project is effectively abandoned?

You are effectively buzzing about it for several years already :P

Bugs are still worth collecting a*nya*way, as they are hard to reproduce.

> Unless you find someone to write a PR

Why find, it would barely be fixed by anyone but me :P
