### ISSUE TITLE
Crash on message

### ISSUE THREAD

**Issue by felixonmars** [majn/telegram-purple#74]
I am getting this crash rather frequently using 43266f4 version:

```
Program received signal SIGSEGV, Segmentation fault.
msg_send_on_answer (TLS=0x5189800, q=0x5d9c320) at tgl/queries.c:883
883       if (M->flags & FLAG_PENDING) {
(gdb) bt
#0  msg_send_on_answer (TLS=0x5189800, q=0x5d9c320) at tgl/queries.c:883
#1  0x00007fffc0823de2 in tglq_query_result (TLS=TLS@entry=0x5189800, id=<optimized out>) at tgl/queries.c:400
#2  0x00007fffc081b9cf in work_rpc_result (c=0x6038de0, msg_id=<optimized out>, TLS=0x5189800) at tgl/mtproto-client.c:856
#3  rpc_execute_answer (TLS=TLS@entry=0x5189800, c=c@entry=0x6038de0, msg_id=<optimized out>) at tgl/mtproto-client.c:952
#4  0x00007fffc081c742 in process_rpc_message (enc=0x7fffc1c3f600 <Response.25010>, len=<optimized out>, c=0x6038de0, TLS=0x5189800)
    at tgl/mtproto-client.c:1136
#5  rpc_execute (TLS=0x5189800, c=0x6038de0, op=<optimized out>, len=<optimized out>) at tgl/mtproto-client.c:1191
#6  0x00007fffc0805670 in try_rpc_read (c=0x6038de0) at tgp-net.c:428
#7  try_read (c=0x6038de0) at tgp-net.c:474
#8  conn_try_read (arg=0x6038de0, source=<optimized out>, cond=<optimized out>) at tgp-net.c:244
#9  0x000000000046978e in ?? ()
#10 0x00007ffff556090d in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#11 0x00007ffff5560ce0 in ?? () from /usr/lib/libglib-2.0.so.0
#12 0x00007ffff5561002 in g_main_loop_run () from /usr/lib/libglib-2.0.so.0
#13 0x00007ffff6823467 in gtk_main () from /usr/lib/libgtk-x11-2.0.so.0
#14 0x0000000000431a1b in main ()
(gdb) f 0
#0  msg_send_on_answer (TLS=0x5189800, q=0x5d9c320) at tgl/queries.c:883
883       if (M->flags & FLAG_PENDING) {
(gdb) p M
$1 = (struct tgl_message *) 0x0
```

Any hints?

**Comment by majn** [comment]
This issue is fixed.
